steps:

- id: "Pull app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/markdown-project-256618/markdown:latest']

- id: "Build app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/markdown-project-256618/markdown:latest', '.']

- id: "Push app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/markdown-project-256618/markdown:latest']

- id: "Deploy new app image"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'markdown', '--image=gcr.io/markdown-project-256618/markdown:latest', '--region=us-central1', '--allow-unauthenticated', '--concurrency=30', '--platform=managed', '--timeout=1m', '--max-instances=12', '--memory=256Mi']
