steps:

- id: "Import index.html prod file"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://markdown_website_conf/index.html', './public/']

- id: "Build app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/personal-website-269509/markdown:latest', '.']

- id: "Push app image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/personal-website-269509/markdown:latest']

- id: "Deploy new app image"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'markdown', '--image=gcr.io/personal-website-269509/markdown:latest', '--region=us-central1', '--allow-unauthenticated', '--concurrency=30', '--platform=managed', '--timeout=1m', '--max-instances=12', '--memory=256Mi']

timeout: 300s