steps:

- id: "install dependency"
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: "Build static files"
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

- id: "Download Express server"
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/markdown-236511/r/github_yoanndelattre_express-server-gcp', './webserver_prod']

- id: "Move Website Markdown Project folder"
  name: 'alpine'
  args: ['sh', '-c', 'cp -rf ./build/. ./webserver_prod/app_files/']

- id: "Move WebsiteMarkdownConfigAppEngine.yaml in webserver_prod folder"
  name: 'alpine'
  args: ['sh', "-c", 'mv ./deploy/WebsiteMarkdownConfigAppEngine.yaml ./webserver_prod/']

- id: "DEPLOY APP ENGINE"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', './webserver_prod/WebsiteMarkdownConfigAppEngine.yaml', './deploy/dispatch.yaml', '--version=1']
