steps:

- id: "Copy robots.txt file"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', "gs://analytics_markdown-box-config/robots.txt", "./public/"]

- id: "Copy sitemap.xml file"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', "gs://analytics_markdown-box-config/sitemap.xml", "./public/"]

- id: "install dependency"
  name: 'gcr.io/cloud-builders/npm'
  args: ['install']

- id: "build static files"
  name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']

- id: "Sync static files in bucket"
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-d', '-r', './build/', 'gs://website_markdown-builded/']

- id: "Download git repo for config App Engine"
  name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://source.developers.google.com/p/markdown-236511/r/Config-App-Engine-Markdown']
  
- id: "DEPLOY ON APP ENGINE"
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['builds', 'submit', '--config', './Config-App-Engine-Markdown/master/cloudbuildDeploy.yaml', './Config-App-Engine-Markdown/']